# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-05 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('app_label', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('app', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventTypes1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_title', models.CharField(blank=True, max_length=50, null=True)),
                ('event_description', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Event_Types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Address1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('apartments', models.IntegerField()),
            ],
            options={
                'db_table': 'Address',
            },
        ),
        migrations.CreateModel(
            name='AdministrativeStuff1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cab_number', models.IntegerField()),
            ],
            options={
                'db_table': 'Administrative_stuff',
            },
        ),
        migrations.CreateModel(
            name='Attendees1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
            ],
            options={
                'db_table': 'Attendees',
            },
        ),
        migrations.CreateModel(
            name='Avatars1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('avatar', models.ImageField(default='C:/xd_team.project/showmanhouseback/oracledbimages/def/pepega.jpg', upload_to='C:/xd_team.project/showmanhouseback/oracledbimages/')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Attendees1')),
            ],
            options={
                'db_table': 'Avatars',
            },
        ),
        migrations.CreateModel(
            name='City1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=50)),
                ('city_state', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'City',
            },
        ),
        migrations.CreateModel(
            name='Country1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Country',
            },
        ),
        migrations.CreateModel(
            name='Discount1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('orders_number', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Attendees1')),
            ],
            options={
                'db_table': 'Discount',
            },
        ),
        migrations.CreateModel(
            name='Employees1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='EntertainingGroup1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('house_per_week', models.IntegerField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Employees1')),
            ],
            options={
                'db_table': 'Entertaining_group',
            },
        ),
        migrations.CreateModel(
            name='FederativeRepublic1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_in_federation', models.CharField(max_length=50)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Country1')),
            ],
            options={
                'db_table': 'Federative_Republics',
            },
        ),
        migrations.CreateModel(
            name='FeeSchedule1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('payment_date', models.DateField()),
                ('payment_amount', models.IntegerField()),
            ],
            options={
                'db_table': 'Fee_Schedule',
            },
        ),
        migrations.CreateModel(
            name='Orders1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Attendees1')),
            ],
            options={
                'db_table': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OurEvents1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('participants', models.IntegerField()),
                ('price', models.IntegerField()),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FeeSchedule1')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.EventTypes1')),
            ],
            options={
                'db_table': 'Our_Events',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=50)),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FeeSchedule1')),
            ],
            options={
                'db_table': 'Payment_Method',
            },
        ),
        migrations.CreateModel(
            name='ShowmanHouse1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('employees_number', models.IntegerField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.EventTypes1')),
            ],
            options={
                'db_table': 'Showman_House',
            },
        ),
        migrations.CreateModel(
            name='Trainee1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Employees1')),
            ],
            options={
                'db_table': 'Trainee',
            },
        ),
        migrations.AddField(
            model_name='orders1',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ShowmanHouse1'),
        ),
        migrations.AddField(
            model_name='orders1',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.EventTypes1'),
        ),
        migrations.AddField(
            model_name='employees1',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ShowmanHouse1'),
        ),
        migrations.AddField(
            model_name='city1',
            name='country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Country1'),
        ),
        migrations.AddField(
            model_name='administrativestuff1',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Employees1'),
        ),
        migrations.AddField(
            model_name='address1',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.City1'),
        ),
        migrations.AddField(
            model_name='address1',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Attendees1'),
        ),
    ]
