# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-04 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('apartments', models.IntegerField()),
            ],
            options={
                'db_table': 'Address',
            },
        ),
        migrations.CreateModel(
            name='AdministrativeStuff',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cab_number', models.IntegerField()),
            ],
            options={
                'db_table': 'Administrative_stuff',
            },
        ),
        migrations.CreateModel(
            name='Attendees',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Attendees',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=50)),
                ('city_state', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'City',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Country',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('orders_number', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Attendees')),
            ],
            options={
                'db_table': 'Discount',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='EntertainingGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('house_per_week', models.IntegerField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Employees')),
            ],
            options={
                'db_table': 'Entertaining_group',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('participants', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'Events',
            },
        ),
        migrations.CreateModel(
            name='FederativeRepublic',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_in_federation', models.CharField(max_length=50)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Country')),
            ],
            options={
                'db_table': 'Federative_Republics',
            },
        ),
        migrations.CreateModel(
            name='FeeSchedule',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('payment_date', models.DateField()),
                ('payment_amount', models.IntegerField()),
            ],
            options={
                'db_table': 'Fee_Schedule',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Attendees')),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=50)),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FeeSchedule')),
            ],
            options={
                'db_table': 'Payment_Method',
            },
        ),
        migrations.CreateModel(
            name='ShowmanHouse',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('employees_number', models.IntegerField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.EventTypes')),
            ],
            options={
                'db_table': 'Showman_House',
            },
        ),
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Employees')),
            ],
            options={
                'db_table': 'Trainee',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ShowmanHouse'),
        ),
        migrations.AddField(
            model_name='order',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.EventTypes'),
        ),
        migrations.AddField(
            model_name='events',
            name='payment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FeeSchedule'),
        ),
        migrations.AddField(
            model_name='events',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.EventTypes'),
        ),
        migrations.AddField(
            model_name='employees',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ShowmanHouse'),
        ),
        migrations.AddField(
            model_name='city',
            name='country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Country'),
        ),
        migrations.AddField(
            model_name='administrativestuff',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Employees'),
        ),
        migrations.AddField(
            model_name='address',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.City'),
        ),
        migrations.AddField(
            model_name='address',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Attendees'),
        ),
    ]
