# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-12 04:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatars1',
            name='avatar',
            field=models.ImageField(default='C:/xd_team.project/showmanhouseback/oracledbimages/ef/pepega.jpg', upload_to=''),
        ),
    ]
