# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-05 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='eventtypes1',
            table='Event_Types1',
        ),
    ]
