# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-12 11:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20190512_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address1',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='api.Attendees1'),
        ),
    ]
