# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-12 18:57
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_auto_20190512_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeschedule1',
            name='created_by',
            field=models.ForeignKey(default=120, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        )
    ]
