# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-12 19:03
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_auto_20190513_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod1',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
