# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-12 20:45
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_auto_20190513_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourevents1',
            name='created_by',
            field=models.ForeignKey(default=120, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feeschedule1',
            name='payment_date',
            field=models.DateField(verbose_name=datetime.datetime(2019, 5, 13, 2, 45, 14, 956110)),
        ),
        migrations.AlterField(
            model_name='ourevents1',
            name='end_date',
            field=models.DateField(verbose_name=datetime.datetime(2019, 5, 13, 2, 45, 14, 960100)),
        ),
        migrations.AlterField(
            model_name='ourevents1',
            name='start_date',
            field=models.DateField(verbose_name=datetime.datetime(2019, 5, 13, 2, 45, 14, 960100)),
        ),
    ]
