# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-13 01:47
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_auto_20190513_0245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatars1Events',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('avatar', models.ImageField(default='C:/xd_team.project/showmanhouseback/oracledbimages/ef/pepega.jpg', upload_to='')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.EventTypes1')),
            ],
            options={
                'db_table': 'EventAvatars',
            },
        ),
    ]
